# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  ROOT_SRC_PYTHON: ./chainforge
  ROOT_SRC_NODE: ./chainforge/react-server

  # value of this variable will be given to the `--dir` flag of the `chainforge serve` command
  ROOT_DIR_ASSET: '{{.ROOT_DIR}}/chainforge_assets/'

includes:
  
  py: '{{.ROOT_SRC_PYTHON}}/Taskfile.yaml'
  
  npm: 
    taskfile: '{{.ROOT_SRC_NODE}}/Taskfile.yaml'
    dir: '{{.ROOT_SRC_NODE}}'